CREATE TABLE `ask_tournaments` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` CHAR(36) NOT NULL,
    `sport_id` CHAR(36) NOT NULL,
    `user_id` BIGINT UNSIGNED NULL,
    `name` VARCHAR(255) NOT NULL,
    `slug_name` VARCHAR(255) NOT NULL,
    `description` VARCHAR(255) NULL,
    `content` LONGTEXT NULL,
    `tournament_type` VARCHAR(255) NULL,
    `startdate` DATETIME(3) NULL,
    `enddate` DATETIME(3) NULL,
    `address` VARCHAR(255) NULL,
    `country_id` BIGINT UNSIGNED NOT NULL,
    `state_id` BIGINT UNSIGNED NOT NULL,
    `city_id` BIGINT UNSIGNED NOT NULL,
    `bannerimage` VARCHAR(255) NULL,
    `thumbnail` VARCHAR(255) NULL,
    `url` VARCHAR(255) NULL,
    `brochure` VARCHAR(255) NULL,
    `prize` VARCHAR(255) NULL,
    `fees` VARCHAR(255) NULL,
    `participation_limit` INTEGER NULL,
    `publish_status` TINYINT NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP(0) NULL,
    `updated_at` TIMESTAMP(0) NULL,
    `deleted_at` TIMESTAMP(0) NULL,

    UNIQUE INDEX `ask_tournaments_uuid_key`(`uuid`),
    UNIQUE INDEX `ask_tournaments_slug_name_key`(`slug_name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
